# Generated by Django 3.2.13 on 2022-12-07 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_rename_mbti_community_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addedcommunity', to=settings.AUTH_USER_MODEL),
        ),
    ]
