# Generated by Django 3.2.13 on 2022-12-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남', '남'), ('여', '여')], default='남', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti1',
            field=models.CharField(choices=[('E', 'E'), ('I', 'I')], default='E', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti2',
            field=models.CharField(choices=[('N', 'N'), ('S', 'S')], default='N', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti3',
            field=models.CharField(choices=[('T', 'T'), ('F', 'F')], default='T', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti4',
            field=models.CharField(choices=[('P', 'P'), ('J', 'J')], default='P', max_length=25),
        ),
    ]
