# Generated by Django 3.2.13 on 2022-12-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mbti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('특징', '특징'), ('상대법', '상대법'), ('주의할 점', '주의할 점')], max_length=50)),
                ('character', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('mbti', models.CharField(choices=[('INTJ', 'INTJ'), ('INFP', 'INFP'), ('ESFP', 'ESFP'), ('ESFJ', 'ESFJ'), ('ISFJ', 'ISFJ'), ('INTP', 'INTP'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ENTP', 'ENTP'), ('ISTP', 'ISTP'), ('ISTJ', 'ISTJ'), ('INFJ', 'INFJ'), ('ENTJ', 'ENTJ'), ('ISFP', 'ISFP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
            ],
        ),
    ]
