# Generated by Django 3.2.13 on 2022-12-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mbti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('특징', '특징'), ('상대법', '상대법'), ('주의할 점', '주의할 점')], max_length=50)),
                ('character', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('mbti', models.CharField(choices=[('ENFJ', 'ENFJ'), ('ISTJ', 'ISTJ'), ('ENTJ', 'ENTJ'), ('ESTP', 'ESTP'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INFP', 'INFP'), ('ENFP', 'ENFP'), ('ISTP', 'ISTP'), ('INFJ', 'INFJ'), ('ESTJ', 'ESTJ'), ('ISFJ', 'ISFJ'), ('ENTP', 'ENTP'), ('ESFP', 'ESFP'), ('ESFJ', 'ESFJ'), ('INTP', 'INTP')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
