# Generated by Django 3.2.13 on 2022-12-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mbti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('특징', '특징'), ('주의할 점', '주의할 점'), ('상대법', '상대법')], max_length=50)),
                ('mbti', models.CharField(choices=[('ESFP', 'ESFP'), ('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ESTP', 'ESTP'), ('INTP', 'INTP'), ('INFJ', 'INFJ'), ('INTJ', 'INTJ'), ('INFP', 'INFP'), ('ISTJ', 'ISTJ'), ('ISFP', 'ISFP'), ('ISPT', 'ISTP'), ('ENTP', 'ENTP')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
