<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-12-07 05:43
=======
# Generated by Django 3.2.13 on 2022-12-07 07:03
>>>>>>> 3cb31ab1070c77de5e20229b0ecd97d91843e82b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
<<<<<<< HEAD
            field=models.CharField(choices=[('ENTJ', 'ENTJ'), ('ESFJ', 'ESFJ'), ('ENTP', 'ENTP'), ('ISPT', 'ISTP'), ('ISFP', 'ISFP'), ('INFJ', 'INFJ'), ('INTJ', 'INTJ'), ('INFP', 'INFP'), ('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('ISFJ', 'ISFJ'), ('ISTJ', 'ISTJ'), ('ENFP', 'ENFP'), ('INTP', 'INTP'), ('ENFJ', 'ENFJ')], max_length=50),
=======
            field=models.CharField(choices=[('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('INTJ', 'INTJ'), ('ESTP', 'ESTP'), ('ISTJ', 'ISTJ'), ('ESFP', 'ESFP'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('ESFJ', 'ESFJ'), ('INFP', 'INFP'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ISPT', 'ISTP'), ('ISFJ', 'ISFJ')], max_length=50),
>>>>>>> 3cb31ab1070c77de5e20229b0ecd97d91843e82b
        ),
    ]
