# Generated by Django 3.2.13 on 2022-12-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('주의할 점', '주의할 점'), ('상대법', '상대법'), ('특징', '특징')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ENTP', 'ENTP'), ('INTP', 'INTP'), ('ESTJ', 'ESTJ'), ('ISTP', 'ISTP'), ('INFJ', 'INFJ'), ('ISFJ', 'ISFJ'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('ESFP', 'ESFP'), ('INTJ', 'INTJ'), ('ISTJ', 'ISTJ'), ('ESFJ', 'ESFJ'), ('ENFP', 'ENFP'), ('ENTJ', 'ENTJ')], max_length=50),
        ),
    ]
