# Generated by Django 3.2.13 on 2022-12-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('특징', '특징'), ('주의할 점', '주의할 점'), ('상대법', '상대법')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('INTP', 'INTP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('INFJ', 'INFJ'), ('ENTP', 'ENTP'), ('ENTJ', 'ENTJ'), ('ISFP', 'ISFP'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('INTJ', 'INTJ'), ('ENFP', 'ENFP'), ('ISTP', 'ISTP')], max_length=50),
        ),
    ]
