# Generated by Django 3.2.13 on 2022-12-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbti',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('특징', '특징'), ('상대법', '상대법'), ('주의할 점', '주의할 점')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('INFJ', 'INFJ'), ('ISFJ', 'ISFJ'), ('ESFP', 'ESFP'), ('ENTP', 'ENTP'), ('ISTJ', 'ISTJ'), ('INFP', 'INFP'), ('ISTP', 'ISTP'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('ENFJ', 'ENFJ'), ('ESTP', 'ESTP'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('ESFJ', 'ESFJ')], max_length=50),
        ),
    ]
