# Generated by Django 3.2.13 on 2022-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ISTJ', 'ISTJ'), ('ESFJ', 'ESFJ'), ('ISTP', 'ISTP'), ('ENFP', 'ENFP'), ('ISFP', 'ISFP'), ('ENTJ', 'ENTJ'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP'), ('INTJ', 'INTJ'), ('ENTP', 'ENTP'), ('INTP', 'INTP'), ('INFJ', 'INFJ')], max_length=50),
        ),
    ]
