# Generated by Django 3.2.13 on 2022-12-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('상대법', '상대법'), ('특징', '특징'), ('주의할 점', '주의할 점')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('ISFJ', 'ISFJ'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('INFJ', 'INFJ'), ('ESFP', 'ESFP'), ('INFP', 'INFP'), ('INTJ', 'INTJ'), ('ISFP', 'ISFP'), ('ENTP', 'ENTP'), ('ISTP', 'ISTP'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ')], max_length=50),
        ),
    ]
