# Generated by Django 3.2.13 on 2022-12-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('주의할 점', '주의할 점'), ('상대법', '상대법'), ('특징', '특징')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ENFJ', 'ENFJ'), ('ENTJ', 'ENTJ'), ('INTJ', 'INTJ'), ('ISPT', 'ISTP'), ('ENTP', 'ENTP'), ('INFP', 'INFP'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('INFJ', 'INFJ'), ('ISFJ', 'ISFJ'), ('ISTJ', 'ISTJ'), ('ISFP', 'ISFP'), ('ESFJ', 'ESFJ'), ('INTP', 'INTP'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP')], max_length=50),
        ),
    ]
