# Generated by Django 3.2.13 on 2022-12-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('특징', '특징'), ('상대법', '상대법'), ('주의할 점', '주의할 점')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ISPT', 'ISTP'), ('ESFP', 'ESFP'), ('INFJ', 'INFJ'), ('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('INTJ', 'INTJ'), ('ENTP', 'ENTP'), ('ENTJ', 'ENTJ'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ISFP', 'ISFP'), ('INTP', 'INTP'), ('ESTJ', 'ESTJ'), ('ISFJ', 'ISFJ')], max_length=50),
        ),
    ]
