# Generated by Django 3.2.13 on 2022-12-07 07:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mbti',

            field=models.CharField(choices=[('INTP', 'INTP'), ('INFJ', 'INFJ'), ('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('INTJ', 'INTJ'), ('ESTP', 'ESTP'), ('ISTJ', 'ISTJ'), ('ESFP', 'ESFP'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('ESFJ', 'ESFJ'), ('INFP', 'INFP'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ISPT', 'ISTP'), ('ISFJ', 'ISFJ')], max_length=50),
        ),
    ]
