# Generated by Django 3.2.13 on 2022-12-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('주의할 점', '주의할 점'), ('상대법', '상대법'), ('특징', '특징')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ESTP', 'ESTP'), ('ESTJ', 'ESTJ'), ('INTJ', 'INTJ'), ('ISFJ', 'ISFJ'), ('ENTJ', 'ENTJ'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('INTP', 'INTP'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ'), ('ENTP', 'ENTP'), ('ENFP', 'ENFP'), ('ISPT', 'ISTP'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ENFJ', 'ENFJ')], max_length=50),
        ),
    ]
