# Generated by Django 3.2.13 on 2022-12-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('특징', '특징'), ('상대법', '상대법'), ('주의할 점', '주의할 점')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ISFJ', 'ISFJ'), ('INFP', 'INFP'), ('ISFP', 'ISFP'), ('ENTP', 'ENTP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ESFP', 'ESFP'), ('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ENFJ', 'ENFJ'), ('INTP', 'INTP'), ('ENFP', 'ENFP')], max_length=50),
        ),
    ]
