# Generated by Django 3.2.13 on 2022-12-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0002_auto_20221209_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('특징', '특징'), ('상대법', '상대법'), ('주의할 점', '주의할 점')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ESFP', 'ESFP'), ('ISFP', 'ISFP'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('INTJ', 'INTJ'), ('ISPT', 'ISTP'), ('ENTJ', 'ENTJ'), ('ISTJ', 'ISTJ'), ('INTP', 'INTP'), ('ENFP', 'ENFP'), ('ESTJ', 'ESTJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ESFJ', 'ESFJ'), ('INFJ', 'INFJ'), ('ISFJ', 'ISFJ')], max_length=50),
        ),
    ]
