# Generated by Django 3.2.13 on 2022-12-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0002_auto_20221214_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('ESTP', 'ESTP'), ('INTP', 'INTP'), ('ENTP', 'ENTP'), ('INFP', 'INFP'), ('INFJ', 'INFJ'), ('ENTJ', 'ENTJ'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ISTJ', 'ISTJ'), ('ISFP', 'ISFP'), ('ENFP', 'ENFP'), ('ESTJ', 'ESTJ'), ('ENFJ', 'ENFJ'), ('ISPT', 'ISTP'), ('ISFJ', 'ISFJ')], max_length=50),
        ),
    ]
