# Generated by Django 3.2.13 on 2022-12-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0002_auto_20221212_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('특징', '특징'), ('상대법', '상대법'), ('주의할 점', '주의할 점')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ISTJ', 'ISTJ'), ('ESFP', 'ESFP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ESTP', 'ESTP'), ('INFJ', 'INFJ'), ('INTJ', 'INTJ'), ('ESTJ', 'ESTJ'), ('ISFP', 'ISFP'), ('INFP', 'INFP'), ('ISPT', 'ISTP'), ('ENTJ', 'ENTJ'), ('ISFJ', 'ISFJ'), ('ESFJ', 'ESFJ'), ('INTP', 'INTP'), ('ENTP', 'ENTP')], max_length=50),
        ),
    ]
