# Generated by Django 3.2.13 on 2022-12-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0002_alter_mbti_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ISTJ', 'ISTJ'), ('ESTP', 'ESTP'), ('ENTP', 'ENTP'), ('ENTJ', 'ENTJ'), ('ISFP', 'ISFP'), ('ISPT', 'ISTP'), ('ISFJ', 'ISFJ'), ('INFP', 'INFP'), ('ENFP', 'ENFP'), ('INTJ', 'INTJ'), ('ESTJ', 'ESTJ'), ('INTP', 'INTP'), ('ENFJ', 'ENFJ'), ('ESFP', 'ESFP'), ('INFJ', 'INFJ')], max_length=50),
        ),
    ]
