# Generated by Django 3.2.13 on 2022-12-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0002_auto_20221213_0102'),
        ('MBTI', '0002_auto_20221213_1136'),
    ]

    operations = [
    ]
