# Generated by Django 3.2.13 on 2022-12-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0003_auto_20221214_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('주의할 점', '주의할 점'), ('상대법', '상대법'), ('특징', '특징')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ISTP', 'ISTP'), ('ENTJ', 'ENTJ'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('INFJ', 'INFJ'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ENFP', 'ENFP'), ('ESTP', 'ESTP'), ('INTP', 'INTP'), ('INTJ', 'INTJ'), ('ENTP', 'ENTP'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ'), ('ENFJ', 'ENFJ'), ('INFP', 'INFP')], max_length=50),
        ),
    ]
