# Generated by Django 3.2.13 on 2022-12-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0003_auto_20221214_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('특징', '특징'), ('주의할 점', '주의할 점'), ('상대법', '상대법')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('INTP', 'INTP'), ('ENFJ', 'ENFJ'), ('ENTP', 'ENTP'), ('ESTP', 'ESTP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('ENTJ', 'ENTJ'), ('ISFP', 'ISFP'), ('ISTP', 'ISTP'), ('INTJ', 'INTJ'), ('ESFP', 'ESFP'), ('ESFJ', 'ESFJ'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('INFJ', 'INFJ'), ('INFP', 'INFP')], max_length=50),
        ),
    ]
