# Generated by Django 3.2.13 on 2022-12-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0003_alter_mbti_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ENFP', 'ENFP'), ('INTJ', 'INTJ'), ('ISPT', 'ISTP'), ('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('ISFP', 'ISFP'), ('INTP', 'INTP'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ'), ('ENFJ', 'ENFJ'), ('ENTJ', 'ENTJ'), ('ISFJ', 'ISFJ'), ('ESFJ', 'ESFJ'), ('ISTJ', 'ISTJ'), ('INFP', 'INFP'), ('ESTJ', 'ESTJ')], max_length=50),
        ),
    ]
