# Generated by Django 3.2.13 on 2022-12-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0003_merge_0002_auto_20221213_0102_0002_auto_20221213_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('상대법', '상대법'), ('특징', '특징'), ('주의할 점', '주의할 점')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ESTP', 'ESTP'), ('INFP', 'INFP'), ('ENTJ', 'ENTJ'), ('ISPT', 'ISTP'), ('ISTJ', 'ISTJ'), ('ESTJ', 'ESTJ'), ('ESFP', 'ESFP'), ('INTJ', 'INTJ'), ('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('INFJ', 'INFJ'), ('INTP', 'INTP'), ('ISFJ', 'ISFJ'), ('ENFP', 'ENFP'), ('ISFP', 'ISFP'), ('ENTP', 'ENTP')], max_length=50),
        ),
    ]
