# Generated by Django 3.2.13 on 2022-12-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0003_alter_mbti_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('ENTJ', 'ENTJ'), ('ESTP', 'ESTP'), ('ENFP', 'ENFP'), ('ESTJ', 'ESTJ'), ('INFJ', 'INFJ'), ('ISFP', 'ISFP'), ('INTP', 'INTP'), ('ISPT', 'ISTP'), ('ESFP', 'ESFP'), ('INFP', 'INFP'), ('ENTP', 'ENTP'), ('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ')], max_length=50),
        ),
    ]
