# Generated by Django 3.2.13 on 2022-12-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0004_auto_20221214_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('특징', '특징'), ('상대법', '상대법'), ('주의할 점', '주의할 점')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ESTP', 'ESTP'), ('ISFJ', 'ISFJ'), ('ISTP', 'ISTP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('ENFJ', 'ENFJ'), ('ENTJ', 'ENTJ'), ('INTP', 'INTP'), ('ESTJ', 'ESTJ'), ('ENFP', 'ENFP'), ('ESFJ', 'ESFJ'), ('ISFP', 'ISFP'), ('ESFP', 'ESFP'), ('INFP', 'INFP'), ('ISTJ', 'ISTJ'), ('ENTP', 'ENTP')], max_length=50),
        ),
    ]
