# Generated by Django 3.2.13 on 2022-12-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0004_alter_mbti_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('INFP', 'INFP'), ('INTP', 'INTP'), ('ESFP', 'ESFP'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ESTP', 'ESTP'), ('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('ENTP', 'ENTP'), ('ISPT', 'ISTP'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('ISTJ', 'ISTJ')], max_length=50),
        ),
    ]
