# Generated by Django 3.2.13 on 2022-12-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0004_auto_20221214_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('INTJ', 'INTJ'), ('ENFP', 'ENFP'), ('ESFJ', 'ESFJ'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('ESTJ', 'ESTJ'), ('ISTJ', 'ISTJ'), ('ESFP', 'ESFP'), ('INFJ', 'INFJ'), ('ENFJ', 'ENFJ'), ('ISFP', 'ISFP'), ('INFP', 'INFP'), ('ISFJ', 'ISFJ'), ('ENTP', 'ENTP'), ('ISTP', 'ISTP'), ('ESTP', 'ESTP')], max_length=50),
        ),
    ]
