# Generated by Django 3.2.13 on 2022-12-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0005_alter_mbti_mbti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('주의할 점', '주의할 점'), ('특징', '특징'), ('상대법', '상대법')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ESFP', 'ESFP'), ('INFP', 'INFP'), ('ENTJ', 'ENTJ'), ('ESFJ', 'ESFJ'), ('ESTJ', 'ESTJ'), ('ISTJ', 'ISTJ'), ('ENFP', 'ENFP'), ('ISPT', 'ISTP'), ('INTJ', 'INTJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('INFJ', 'INFJ'), ('INTP', 'INTP')], max_length=50),
        ),
    ]
