# Generated by Django 3.2.13 on 2022-12-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0005_auto_20221214_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('특징', '특징'), ('주의할 점', '주의할 점'), ('상대법', '상대법')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ENFP', 'ENFP'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('ENFJ', 'ENFJ'), ('INFP', 'INFP'), ('ESFP', 'ESFP'), ('ESFJ', 'ESFJ'), ('ISTJ', 'ISTJ'), ('ESTJ', 'ESTJ'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INFJ', 'INFJ'), ('ENTP', 'ENTP'), ('ESTP', 'ESTP'), ('ISTP', 'ISTP')], max_length=50),
        ),
    ]
