# Generated by Django 3.2.13 on 2022-12-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0006_auto_20221214_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='board',
            field=models.CharField(choices=[('주의할 점', '주의할 점'), ('상대법', '상대법'), ('특징', '특징')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='mbti',
            field=models.CharField(choices=[('ISFP', 'ISFP'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('ENFJ', 'ENFJ'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ISTP', 'ISTP'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ENTP', 'ENTP'), ('ISTJ', 'ISTJ'), ('INTJ', 'INTJ')], max_length=50),
        ),
    ]
